Repository ETBassist/Crate, pull requests merged in 2021-02, with the labels that each got.

#31 Create pull_request_template.md
  .github/pull_request_template.md
Labels: documentation

#49 Feature profile additions
  code/web/package-lock.json
  code/web/package.json
  code/web/public/css/common.css
  code/web/public/images/profile_placeholder.jpg
  code/web/src/modules/admin/product/CreateOrEdit.js
  code/web/src/modules/pages/Onboarding.js
  code/web/src/modules/subscription/api/actions.js
  code/web/src/modules/user/Deliveries.js
  code/web/src/modules/user/Profile.js
  code/web/src/modules/user/ProfileEdit.js
  code/web/src/modules/user/api/actions.js
  code/web/src/modules/user/api/state.js
  code/web/src/modules/user/states.js
  code/web/src/setup/routes/user.js
  code/web/src/setup/server/load-modules.js
  code/web/src/setup/store.js
  code/web/src/ui/Avatar/Avatar.js
  code/web/src/ui/grid/GridCell.js
  code/web/src/ui/image/Tile.js
  code/web/storybook/config.js
  code/web/storybook/stories/modal.js
Labels: React/Component, Redux, data display, enhancement, fix, styles

#52 Feature/update delivery date
  code/api/package-lock.json
  code/api/src/seeders/5-deliveries.js
  code/web/src/modules/user/Deliveries.js
  code/web/src/modules/user/Profile.js
  code/web/src/modules/user/ProfileEdit.js
  code/web/src/modules/user/api/actions.js
  code/web/src/ui/modal/Modal.js
  code/web/src/ui/modal/ModalForm.js
Labels: React/Component, enhancement, styles
